name: Test JavaScript function

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Check out the repository

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Set up Node.js
        with:
          node-version: '20.x' # Use Node.js version 20
      - name: Install dependencies
        run: npm ci

      - name: Run the JavaScript script
        run: node src/index.js # Execute the script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GA4_PROPERTY_ID: ${{ secrets.GA4_PROPERTY_ID }}
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
